[build]
  command = "npm run build"
  publish = "dist/payment-test/browser"

[[headers]]
  # Define headers for all paths under "/*"
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"